services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - kosmos-network

networks:
  kosmos-network:
    driver: bridge
